# Generated by Django 4.2.29 on 2026-03-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='아이디(ID)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('role', models.CharField(choices=[('MASTER', '마스터'), ('OWNER', '점주'), ('USER', 'End-user')], default='USER', max_length=10, verbose_name='사용자 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 페이지 접근 권한')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '통합 계정',
                'verbose_name_plural': '통합 계정 목록',
            },
        ),
        migrations.CreateModel(
            name='ShopOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자등록번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('CHOCO', '초콜릿'), ('MACARON', '마카롱'), ('TART', '타르트'), ('GATEAU', '갸또')], default='CHOCO', max_length=10, verbose_name='회원 등급')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enduser_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
